/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DSA;

public class App {
    public static void main(String[] args) {
        String[] s = {"h","e","l","l","o"};
        int limit = s.length;
        for (int i = 0; i < limit; i++){
            if (i != 0){
                System.out.println(s[s.length - i - 1]);
            } else {
                System.out.println(s[s.length - 1]);
            }
        }
    }
}
